/**
 *
 *  @file Toolchain.cpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.  All rights reserved.
 *  https://github.com/vixcpp/vix
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 *  Vix.cpp
 *
 *  Build graph task model
 *
 */
#include <vix/engine/Toolchain.hpp>

#include <sstream>
#include <string>

#include "ExecutableLookup.hpp"

namespace vix::engine
{
  std::string infer_processor_from_triple(std::string_view triple)
  {
    if (triple.rfind("aarch64", 0) == 0)
      return "aarch64";
    if (triple.rfind("arm", 0) == 0)
      return "arm";
    if (triple.rfind("x86_64", 0) == 0)
      return "x86_64";
    if (triple.rfind("riscv64", 0) == 0)
      return "riscv64";
    return "unknown";
  }

  std::string toolchain_contents_for_triple(
      const std::string &triple,
      const std::string &sysroot)
  {
    const std::string proc = infer_processor_from_triple(triple);

    std::ostringstream tc;

    tc << "# Auto-generated by Vix (vix build --target " << triple << ")\n";
    tc << "set(CMAKE_SYSTEM_NAME Linux)\n";
    tc << "set(CMAKE_SYSTEM_PROCESSOR \"" << proc << "\")\n\n";

    if (!sysroot.empty())
    {
      tc << "set(CMAKE_SYSROOT \"" << sysroot << "\")\n";
      tc << "set(CMAKE_FIND_ROOT_PATH \"" << sysroot << "\")\n";
      tc << "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\n";
      tc << "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\n";
      tc << "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\n\n";
    }

    tc << "set(VIX_TARGET_TRIPLE \"" << triple
       << "\" CACHE STRING \"Vix target triple\")\n\n";

    tc << "set(CMAKE_C_COMPILER   \"" << triple
       << "-gcc\" CACHE FILEPATH \"\" FORCE)\n";
    tc << "set(CMAKE_CXX_COMPILER \"" << triple
       << "-g++\" CACHE FILEPATH \"\" FORCE)\n";
    tc << "set(CMAKE_AR           \"" << triple
       << "-ar\"  CACHE FILEPATH \"\" FORCE)\n";
    tc << "set(CMAKE_RANLIB       \"" << triple
       << "-ranlib\" CACHE FILEPATH \"\" FORCE)\n";
    tc << "set(CMAKE_STRIP        \"" << triple
       << "-strip\"  CACHE FILEPATH \"\" FORCE)\n\n";

    tc << "set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)\n";

    return tc.str();
  }

  std::vector<std::string> detect_available_targets()
  {
    static const std::vector<std::string> known = {
        "x86_64-linux-gnu",
        "aarch64-linux-gnu",
        "arm-linux-gnueabihf",
        "riscv64-linux-gnu"};

    std::vector<std::string> out;
    out.reserve(known.size());

    for (const auto &target : known)
    {
      if (detail::executable_on_path(target + "-gcc") &&
          detail::executable_on_path(target + "-g++"))
      {
        out.push_back(target);
      }
    }

    return out;
  }
} // namespace vix::engine
